spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: lobna
    password: lobna123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
server:
  port: 8585
logging:
  level:
    org.springframework.web: DEBUG